apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-deployment
spec:
  selector:
    matchLabels:
      app: mission-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: mission-deployment

    spec:
      containers:
      - name: mission-deployment
        image: sahilbonami/mission:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mission-svcc
spec:
  selector:
    app: mission-deployment
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
 
  
      
