apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role
  namespace: web-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role 
  name: app-role
subjects: 
- namespace: web-app
  kind: ServiceAccount
  name: jenkins